# Generated by Django 4.1.7 on 2023-05-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='errorreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=65)),
                ('code', models.CharField(max_length=2)),
                ('page', models.CharField(max_length=2)),
                ('error', models.CharField(max_length=100)),
                ('details', models.CharField(blank=True, max_length=500, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='errorreport/')),
            ],
        ),
        migrations.CreateModel(
            name='giveawaycontroller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('season', models.CharField(max_length=1)),
                ('title', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='giveawayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default='aaa', max_length=30)),
                ('user', models.CharField(default='aaa', max_length=64)),
                ('pack', models.CharField(max_length=1)),
                ('theme', models.CharField(max_length=1)),
                ('pos', models.PositiveIntegerField()),
                ('posall', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='kwamnaijai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=65)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1)),
                ('packname', models.CharField(default='Packname', max_length=20)),
                ('grade', models.CharField(default='0', max_length=1)),
                ('season', models.CharField(default='0', max_length=1)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=65)),
                ('code', models.CharField(max_length=1)),
                ('text', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sharebox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=65)),
                ('subject', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=200)),
                ('status', models.CharField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='sheetfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1)),
                ('order', models.CharField(default='0', max_length=1)),
                ('theme', models.CharField(default='0', max_length=2)),
                ('sub', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='sheet/')),
            ],
        ),
        migrations.CreateModel(
            name='theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0', max_length=1)),
                ('theme', models.CharField(max_length=30)),
                ('preview', models.ImageField(upload_to='theme/')),
                ('hex1', models.CharField(max_length=7)),
                ('hex2', models.CharField(max_length=7)),
                ('hex3', models.CharField(max_length=7)),
                ('hex4', models.CharField(max_length=7)),
                ('hex5', models.CharField(max_length=7)),
                ('hex6', models.CharField(max_length=7)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง'), ('LGBTQ+', 'LGBTQ+'), ('ไม่ระบุ', 'ไม่ระบุ')], default='ไม่ระบุ', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('pwd', models.CharField(max_length=30)),
                ('rememberme', models.BooleanField(default=False, null=True)),
                ('ig', models.CharField(blank=True, max_length=50, null=True)),
                ('igsecret', models.CharField(max_length=50, null=True)),
                ('relation', models.CharField(blank=True, max_length=20, null=True)),
                ('token', models.PositiveIntegerField(default=3)),
                ('numsheetreq', models.PositiveIntegerField(default=0)),
                ('numpresentsent', models.PositiveIntegerField(default=0)),
                ('numsharebox', models.PositiveIntegerField(default=0)),
                ('meetadmin', models.BooleanField(default=False)),
                ('profilepic', models.ImageField(blank=True, default='profilepic/default', null=True, upload_to='profilepic/')),
            ],
        ),
    ]
