# Generated by Django 4.1.7 on 2023-06-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='giveawaycontroller2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('warning', models.CharField(default=None, max_length=50, null=True)),
                ('season', models.CharField(max_length=1)),
                ('title', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='giveawaycontroller',
            name='warning',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
